### ISSUE TITLE
Rate limiting error

### ISSUE THREAD

**Issue by MoriZalev** [maxbeyer1/CryptoArbitrageScanner#1]
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.coingecko.com/api/v3/coins/binance-usd/tickers
127.0.0.1 - - [31/May/2022 19:56:10] "POST /_dash-update-component HTTP/1.1" 500 -

**Comment by maxbeyer1** [comment]
This is a known issue that occurs due to CoinGecko's [rate limiting](https://www.coingecko.com/en/api/pricing) for their API. To avoid this do not load the page more than once a minute (the automatic refresh will do this for you so you do not need to reload). If you need more immediate data you will have to purchase an API plan and follow the steps to install the app locally with your API key.

**Comment by MoriZalev** [comment]
I used this software for a long time, I did not find a single difference, what could be the problem?

**Comment by maxbeyer1** [comment]
Pushed an update that should resolve it, but you'll see fewer possible trades as CoinGecko has changed its rate limits. Again, you can use your own API key if you want to avoid this.

**Comment by MoriZalev** [comment]
Hello, when running "app.py" the same error occurs as before.

**Comment by maxbeyer1** [comment]
Pushed a new update, let me know if that resolves it.

**Comment by MoriZalev** [comment]
how often does he find the difference in arbitrage ? I haven't found anything in 3 hours

![image](https://user-images.githubusercontent.com/106540747/173256680-bb5a6fe6-20ac-42bb-bded-5ea3939e1914.png)
